CREATE TABLE aircraft
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration     VARCHAR(10)                             NOT NULL,
    aircraft_type_id BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_aircraft PRIMARY KEY (id)
);

ALTER TABLE aircraft
    ADD CONSTRAINT uc_aircraft_registration UNIQUE (registration);

ALTER TABLE aircraft
    ADD CONSTRAINT FK_AIRCRAFT_ON_AIRCRAFTTYPE FOREIGN KEY (aircraft_type_id) REFERENCES aircraft_type (id);