CREATE TABLE airport
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    icao_code    VARCHAR(4)                              NOT NULL,
    iata_code    VARCHAR(3),
    name         VARCHAR(255)                            NOT NULL,
    city         VARCHAR(255),
    country_code VARCHAR(2)                              NOT NULL,
    latitude     DOUBLE PRECISION                        NOT NULL,
    longitude    DOUBLE PRECISION                        NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_airport PRIMARY KEY (id)
);

ALTER TABLE airport
    ADD CONSTRAINT uc_airport_icaocode UNIQUE (icao_code);