CREATE TABLE route
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    origin_id      BIGINT                                  NOT NULL,
    destination_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_route PRIMARY KEY (id)
);

ALTER TABLE route
    ADD CONSTRAINT uc_route_origin_destination UNIQUE (origin_id, destination_id);

ALTER TABLE route
    ADD CONSTRAINT FK_ROUTE_ON_DESTINATION FOREIGN KEY (destination_id) REFERENCES airport (id);

ALTER TABLE route
    ADD CONSTRAINT FK_ROUTE_ON_ORIGIN FOREIGN KEY (origin_id) REFERENCES airport (id);