CREATE TABLE flight
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flight_number            VARCHAR(255)                            NOT NULL,
    route_id                 BIGINT                                  NOT NULL,
    scheduled_departure_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    scheduled_arrival_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    actual_departure_time    TIMESTAMP WITHOUT TIME ZONE,
    actual_arrival_time      TIMESTAMP WITHOUT TIME ZONE,
    status                   VARCHAR(255)                            NOT NULL,
    airline                  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_flight PRIMARY KEY (id)
);

ALTER TABLE flight
    ADD CONSTRAINT FK_FLIGHT_ON_ROUTE FOREIGN KEY (route_id) REFERENCES route (id);